# Question 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
numbers = np.arange(2,50,3)
print(numbers)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [8]:
list1=[]
list2=[]
for i in range(10):
    input_val=int(input())
    if i<5:
        list1.append(input_val)
    if i>=5:
        list2.append(input_val)
list1 = np.array(list1)
list2 = np.array(list2)
concatenated_list = np.concatenate((list1,list2))
print(np.sort(concatenated_list))

78
45
98
34
12
65
47
36
321
123
[ 12  34  36  45  47  65  78  98 123 321]


# Question 3:
Write a code snippet to find the dimensions of a ndarray and its size.


In [18]:
list1 = np.arange(31,36,1)
list2 = np.arange(11,16,1)
arr = np.array([list1,list2])
print(arr.ndim)
print(arr.size)


2
10


# Question 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [56]:
arr = np.arange(10)
#using reshape
arr1 = np.reshape(arr,(2,5))
print(arr1)
print(" Array shape:",arr1.shape)
#using expand_dims
arr2 = np.expand_dims(arr,axis=0)
print(arr2)
print("Array shape:",arr2.shape)
#using newaxis
print(arr[np.newaxis,:])
print("Array shape:",arr[np.newaxis,:].shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
 Array shape: (2, 5)
[[0 1 2 3 4 5 6 7 8 9]]
Array shape: (1, 10)
[[0 1 2 3 4 5 6 7 8 9]]
Array shape: (1, 10)


# Question 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack() 

In [67]:
arr = np.arange(4).reshape(2,2)
arr2 = np.arange(10,50,10).reshape(2,2)
print(np.hstack((arr,arr2)))
print(np.vstack((arr,arr2)))

[[ 0  1 10 20]
 [ 2  3 30 40]]
[[ 0  1]
 [ 2  3]
 [10 20]
 [30 40]]


# Question 6:
How to get unique items and counts of unique items?

In [72]:
arr = np.array([2,3,2,5,2,6,7,10,1,1,20])
print(np.unique(arr))
print(len(np.unique(arr)))

[ 1  2  3  5  6  7 10 20]
8
